name: core-crucible-ci

on:
  workflow_call:
    inputs:
      ci_target:
        required: true
        type: string
      ci_target_dir:
        required: false
        type: string
        default: ""
      crucible_ci_test:
        required: false
        type: string
        default: "no"
      ci_target_branch:
        required: true
        type: string
      crucible_ci_test_branch:
        required: false
        type: string
      github_workspace:
        required: true
        type: string
      userenv_filter:
        required: false
        type: string
        default: "all"
      release:
        required: false
        type: string
        default: "upstream"
      ci_built_controller:
        required: false
        type: string
        default: "no"
      ci_built_controller_tag:
        required: false
        type: string
        default: "--"
    secrets:
      registry_auth:
        required: false
      weekly_ci_registry_auth:
        required: false
      ci_registry_auth:
        required: false
      production_registry_auth:
        required: false
      quay_oauth_token:
        required: false

concurrency:
  group: ${{ inputs.crucible_ci_test }}/${{ inputs.ci_target }}/${{ github.ref }}/core-crucible-ci/${{ inputs.release }}
  cancel-in-progress: true

env:
  GITHUB_WORKSPACE: ${{ inputs.github_workspace }}

jobs:
  gen-params:
    runs-on: [ self-hosted, workflow-overhead ]
    timeout-minutes: 10
    outputs:
      github_hosted_jobs: ${{ steps.get-job-parameters-github.outputs.jobs }}
      self_hosted_jobs: ${{ steps.get-job-parameters-self-hosted.outputs.jobs }}
      ci_target_dir: ${{ steps.set-ci-target-dir.outputs.ci-target-dir }}
      timeout_minutes: ${{ steps.determine-timeout-minutes.outputs.timeout-minutes }}
    steps:

    - name: checkout crucible default
      if: ${{ inputs.ci_target != 'crucible' && inputs.release == 'upstream' }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/crucible
        ref: master
        path: crucible
    - name: checkout crucible ci_target
      if: ${{ inputs.ci_target == 'crucible' && inputs.release == 'upstream' }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/${{ inputs.ci_target }}
        ref: ${{ inputs.ci_target_branch }}
        path: crucible
        fetch-depth: 2
    - name: checkout crucible release
      if: ${{ inputs.release != 'upstream' }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/crucible
        ref: ${{ inputs.release }}
        path: crucible

    - name: checkout workshop default
      if: ${{ inputs.ci_target != 'workshop' && inputs.release == 'upstream' }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/workshop
        ref: master
        path: workshop
    - name: checkout workshop ci_target
      if: ${{ inputs.ci_target == 'workshop' && inputs.release == 'upstream' }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/${{ inputs.ci_target }}
        ref: ${{ inputs.ci_target_branch }}
        path: workshop
    - name: checkout workshop release
      if: ${{ inputs.release != 'upstream' }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/workshop
        ref: ${{ inputs.release }}
        path: workshop

    - name: checkout crucible-ci default
      if: ${{ inputs.ci_target != 'crucible-ci' && inputs.crucible_ci_test != 'yes' }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/crucible-ci
        ref: main
        path: crucible-ci
    - name: checkout crucible-ci ci_target
      if: ${{ inputs.ci_target == 'crucible-ci' && inputs.crucible_ci_test != 'yes' }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/${{ inputs.ci_target }}
        ref: ${{ inputs.ci_target_branch }}
        path: crucible-ci
    - name: checkout crucible-ci crucible_ci_test
      if: ${{ inputs.crucible_ci_test == 'yes' }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/crucible-ci
        ref: ${{ inputs.crucible_ci_test_branch }}
        path: crucible-ci

    - name: checkout rickshaw default
      if: ${{ inputs.ci_target != 'rickshaw' && inputs.release == 'upstream' }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/rickshaw
        ref: master
        path: rickshaw
    - name: checkout rickshaw ci_target
      if: ${{ inputs.ci_target == 'rickshaw' && inputs.release == 'upstream' }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/${{ inputs.ci_target }}
        ref: ${{ inputs.ci_target_branch }}
        path: rickshaw
        fetch-depth: 2
    - name: checkout rickshaw release
      if: ${{ inputs.release != 'upstream' }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/rickshaw
        ref: ${{ inputs.release }}
        path: rickshaw

    - name: checkout toolbox default
      if: ${{ inputs.ci_target != 'toolbox' && inputs.release == 'upstream' }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/toolbox
        ref: main
        path: toolbox
    - name: checkout toolbox ci_target
      if: ${{ inputs.ci_target == 'toolbox' && inputs.release == 'upstream' }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/${{ inputs.ci_target }}
        ref: ${{ inputs.ci_target_branch }}
        path: toolbox
    - name: checkout toolbox release
      if: ${{ inputs.release != 'upstream' }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/toolbox
        ref: ${{ inputs.release }}
        path: toolbox

    - name: run get-job-parameters github
      id: get-job-parameters-github
      uses: ./crucible-ci/.github/actions/get-job-parameters
      with:
        runner-type: "github"
        userenv-filter: ${{ inputs.userenv_filter }}
        rickshaw-directory: "./rickshaw"
        toolbox-directory: "./toolbox"
    - name: run get-job-parameters self-hosted
      id: get-job-parameters-self-hosted
      uses: ./crucible-ci/.github/actions/get-job-parameters
      with:
        runner-type: "self-hosted"
        runner-tags: "cpu-partitioning,remotehosts"
        userenv-filter: ${{ inputs.userenv_filter }}
        rickshaw-directory: "./rickshaw"
        toolbox-directory: "./toolbox"

    - name: set ci_target_dir
      id: set-ci-target-dir
      run: |
        if [ "${{ inputs.ci_target_dir }}" == "" ]; then
          echo "Setting ci-target-dir to the value of inputs.ci_target [${{ inputs.ci_target }} ]"
          echo "ci-target-dir=${{ inputs.ci_target }}" >> $GITHUB_OUTPUT
        else
          echo "Setting ci-target-dir to the value of inputs.ci_target_dir [${{ inputs.ci_target_dir }} ]"
          echo "ci-target-dir=${{ inputs.ci_target_dir }}" >> $GITHUB_OUTPUT
        fi

    - name: determine timeout-minutes
      id: determine-timeout-minutes
      run: |
        if [ "${{ inputs.ci_built_controller }}" == "yes" ]; then
          build_controller_timeout_minutes=150
          echo "Setting timeout-minutes to the build controller value of '${build_controller_timeout_minutes}'"
          echo "timeout-minutes=${build_controller_timeout_minutes}" >> $GITHUB_OUTPUT
        else
          no_build_controller_timeout_minutes=90
          echo "Setting timeout-minutes to the no build controller value of '${no_build_controller_timeout_minutes}'"
          echo "timeout-minutes=${no_build_controller_timeout_minutes}" >> $GITHUB_OUTPUT
        fi

  display-params:
    runs-on: [ self-hosted, workflow-overhead ]
    timeout-minutes: 10
    needs: gen-params
    steps:
    - name: Display github_hosted_jobs
      run: echo '${{ needs.gen-params.outputs.github_hosted_jobs }}' | jq .
    - name: Display self_hosted_jobs
      run: echo '${{ needs.gen-params.outputs.self_hosted_jobs }}' | jq .
    - name: Display ci_target_dir
      run: echo '${{ needs.gen-params.outputs.ci_target_dir }}'
    - name: Display timeout_minutes
      run: echo '${{ needs.gen-params.outputs.timeout_minutes }}'

  github-runners:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(needs.gen-params.outputs.timeout_minutes) }}
    needs:
    - gen-params
    - display-params
    strategy:
      fail-fast: false
      matrix:
        job: ${{ fromJSON(needs.gen-params.outputs.github_hosted_jobs) }}
    steps:
    - name: Matrix Parameters => (${{ matrix.job.enabled }}, ${{ matrix.job.endpoint }}, ${{ matrix.job.benchmark }}, ${{ matrix.job.userenv }})
      run: |
        echo "enabled=${{ matrix.job.enabled }}"
        echo "endpoint=${{ matrix.job.endpoint }}"
        echo "benchmark=${{ matrix.job.benchmark }}"
        echo "userenv=${{ matrix.job.userenv }}"

    - name: checkout ${{ needs.gen-params.outputs.ci_target_dir }} ci_target
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/${{ needs.gen-params.outputs.ci_target_dir }}
        ref: ${{ inputs.ci_target_branch }}
        path: ${{ needs.gen-params.outputs.ci_target_dir }}

    - name: checkout crucible-ci default
      if: ${{ inputs.ci_target != 'crucible-ci' && inputs.crucible_ci_test != 'yes' }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/crucible-ci
        ref: main
        path: crucible-ci
    - name: checkout crucible-ci crucible_ci_test
      if: ${{ inputs.ci_target != 'crucible-ci' && inputs.crucible_ci_test == 'yes' }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/crucible-ci
        ref: ${{ inputs.crucible_ci_test_branch }}
        path: crucible-ci

    - name: import weekly ci secret
      env:
        ENGINE_REGISTRY_AUTH_SECRET: ${{ secrets.weekly_ci_registry_auth }}
      if: ${{ env.ENGINE_REGISTRY_AUTH_SECRET != '' }}
      run: sudo bash -c "echo \"$ENGINE_REGISTRY_AUTH_SECRET\" > /root/crucible-weekly-ci-engines-token.json"
    - name: import ci secret
      env:
        ENGINE_REGISTRY_AUTH_SECRET: ${{ secrets.registry_auth != '' && secrets.registry_auth || secrets.ci_registry_auth }}
      if: ${{ env.ENGINE_REGISTRY_AUTH_SECRET != '' }}
      run: sudo bash -c "echo \"$ENGINE_REGISTRY_AUTH_SECRET\" > /root/crucible-ci-engines-token.json"
    - name: import production secret
      env:
        ENGINE_REGISTRY_AUTH_SECRET: ${{ secrets.production_registry_auth }}
      if: ${{ env.ENGINE_REGISTRY_AUTH_SECRET != '' }}
      run: sudo bash -c "echo \"$ENGINE_REGISTRY_AUTH_SECRET\" > /root/crucible-production-engines-token.json"

    - name: import quay oath token
      env:
        QUAY_OAUTH_TOKEN: ${{ secrets.quay_oauth_token }}
      if: ${{ env.QUAY_OAUTH_TOKEN != '' }}
      run: sudo bash -c "echo \"$QUAY_OAUTH_TOKEN\" > /root/quay-oauth.token"

    - name: run crucible-ci->integration-tests
      if: ${{ matrix.job.enabled }}
      uses: ./crucible-ci/.github/actions/integration-tests
      with:
        artifact_tag: "${{ inputs.ci_target }}__github-runners__${{ matrix.job.endpoint }}-${{ matrix.job.benchmark }}-${{ matrix.job.userenv }}-${{ inputs.release }}"
        ci_endpoint: "${{ matrix.job.endpoint }}"
        scenarios: "${{ matrix.job.benchmark }}"
        userenvs: "${{ matrix.job.userenv }}"
        ci_target: "${{ inputs.ci_target }}"
        ci_target_dir: ${{ github.workspace }}/${{ needs.gen-params.outputs.ci_target_dir }}
        ci_controller: ${{ inputs.ci_built_controller }}
        controller_tag: ${{ inputs.ci_built_controller_tag }}
        crucible_release: "${{ inputs.release }}"
    - name: skip crucible-ci->integration-tests
      if: ${{ ! matrix.job.enabled }}
      run: echo "crucible-ci->integration-tests not enabled"

  self-hosted-runners:
    runs-on: [ self-hosted, cpu-partitioning, remotehosts ]
    timeout-minutes: ${{ fromJSON(needs.gen-params.outputs.timeout_minutes) }}
    needs:
    - gen-params
    - display-params
    strategy:
      fail-fast: false
      matrix:
        job: ${{ fromJSON(needs.gen-params.outputs.self_hosted_jobs) }}
    steps:
    - name: Matrix Parameters => (${{ matrix.job.enabled }}, ${{ matrix.job.endpoint }}, ${{ matrix.job.benchmark }}, ${{ matrix.job.userenv }})
      run: |
        echo "enabled=${{ matrix.job.enabled }}"
        echo "endpoint=${{ matrix.job.endpoint }}"
        echo "benchmark=${{ matrix.job.benchmark }}"
        echo "userenv=${{ matrix.job.userenv }}"

    - name: checkout ${{ needs.gen-params.outputs.ci_target_dir }} ci_target
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/${{ needs.gen-params.outputs.ci_target_dir }}
        ref: ${{ inputs.ci_target_branch }}
        path: ${{ needs.gen-params.outputs.ci_target_dir }}

    - name: checkout crucible-ci default
      if: ${{ inputs.ci_target != 'crucible-ci' && inputs.crucible_ci_test != 'yes' }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/crucible-ci
        ref: main
        path: crucible-ci
    - name: checkout crucible-ci crucible_ci_test
      if: ${{ inputs.ci_target != 'crucible-ci' && inputs.crucible_ci_test == 'yes' }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/crucible-ci
        ref: ${{ inputs.crucible_ci_test_branch }}
        path: crucible-ci

    - name: import weekly ci secret
      env:
        ENGINE_REGISTRY_AUTH_SECRET: ${{ secrets.weekly_ci_registry_auth }}
      if: ${{ env.ENGINE_REGISTRY_AUTH_SECRET != '' }}
      run: sudo bash -c "echo \"$ENGINE_REGISTRY_AUTH_SECRET\" > /root/crucible-weekly-ci-engines-token.json"
    - name: import ci secret
      env:
        ENGINE_REGISTRY_AUTH_SECRET: ${{ secrets.registry_auth != '' && secrets.registry_auth || secrets.ci_registry_auth }}
      if: ${{ env.ENGINE_REGISTRY_AUTH_SECRET != '' }}
      run: sudo bash -c "echo \"$ENGINE_REGISTRY_AUTH_SECRET\" > /root/crucible-ci-engines-token.json"
    - name: import production secret
      env:
        ENGINE_REGISTRY_AUTH_SECRET: ${{ secrets.production_registry_auth }}
      if: ${{ env.ENGINE_REGISTRY_AUTH_SECRET != '' }}
      run: sudo bash -c "echo \"$ENGINE_REGISTRY_AUTH_SECRET\" > /root/crucible-production-engines-token.json"

    - name: import quay oath token
      env:
        QUAY_OAUTH_TOKEN: ${{ secrets.quay_oauth_token }}
      if: ${{ env.QUAY_OAUTH_TOKEN != '' }}
      run: sudo bash -c "echo \"$QUAY_OAUTH_TOKEN\" > /root/quay-oauth.token"

    - name: run crucible-ci->integration-tests
      if: ${{ matrix.job.enabled }}
      uses: ./crucible-ci/.github/actions/integration-tests
      with:
        artifact_tag: "${{ inputs.ci_target }}__self-hosted-runners__${{ matrix.job.endpoint }}-${{ matrix.job.benchmark }}-${{ matrix.job.userenv }}-${{ inputs.release }}"
        ci_endpoint: "${{ matrix.job.endpoint }}"
        scenarios: "${{ matrix.job.benchmark }}"
        userenvs: "${{ matrix.job.userenv }}"
        ci_target: "${{ inputs.ci_target }}"
        ci_target_dir: ${{ github.workspace }}/${{ needs.gen-params.outputs.ci_target_dir }}
        ci_controller: ${{ inputs.ci_built_controller }}
        controller_tag: ${{ inputs.ci_built_controller_tag }}
        crucible_release: "${{ inputs.release }}"
    - name: skip crucible-ci->integration-tests
      if: ${{ ! matrix.job.enabled }}
      run: echo "crucible-ci->integration-tests not enabled"

  core-crucible-ci-complete:
    runs-on: [ self-hosted, workflow-overhead ]
    timeout-minutes: 10
    needs:
    - github-runners
    - self-hosted-runners
    steps:
    - name: Confirm Success
      run: echo "core-crucible-ci-complete"
