name: faux-crucible-ci

on:
  pull_request:
    branches: [ main ]
    paths:
      - LICENSE
      - '**.md'
      - .github/workflows/faux-crucible-ci.yaml
      - .github/workflows/faux-benchmark-crucible-ci.yaml
      - .github/workflows/faux-core-crucible-ci.yaml
      - .github/workflows/faux-tool-crucible-ci.yaml
      - '.github/runners/**'
      - 'docs/**'

jobs:
  test-benchmark-crucible-ci-complete:
    runs-on: [ self-hosted, workflow-overhead ]
    steps:
    - run: 'echo "No build required" '

  test-core-crucible-ci-complete:
    runs-on: [ self-hosted, workflow-overhead ]
    steps:
    - run: 'echo "No build required" '

  test-tool-crucible-ci-complete:
    runs-on: [ self-hosted, workflow-overhead ]
    steps:
    - run: 'echo "No build required" '
