name: test-tool-crucible-ci

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - LICENSE
      - '**.md'
      - .github/workflows/faux-crucible-ci.yaml
      - .github/workflows/faux-benchmark-crucible-ci.yaml
      - .github/workflows/faux-core-crucible-ci.yaml
      - .github/workflows/faux-tool-crucible-ci.yaml
      - '.github/runners/**'
      - 'docs/**'
  workflow_dispatch:

jobs:
  call-tool-crucible-ci:
    strategy:
      fail-fast: false
      matrix:
        repos:
        - tool: "sysstat"
          branch: "master"
        - tool: "procstat"
          branch: "master"
    uses: ./.github/workflows/tool-crucible-ci.yaml
    with:
      ci_target: "${{ matrix.repos.tool }}"
      ci_target_branch: "${{ matrix.repos.branch }}"
      crucible_ci_test: "yes"
      crucible_ci_test_branch: "${{ github.ref }}"
      github_workspace: "$GITHUB_WORKSPACE"
    secrets:
      ci_registry_auth: ${{ secrets.CRUCIBLE_CI_ENGINES_REGISTRY_AUTH }}
      quay_oauth_token: ${{ secrets.CRUCIBLE_QUAYIO_OAUTH_TOKEN }}

  test-tool-crucible-ci-complete:
    runs-on: [ self-hosted, workflow-overhead ]
    needs: call-tool-crucible-ci
    steps:
    - name: Confirm Success
      run: echo "test-tool-crucible-ci-complete"
