name: test-core-crucible-ci

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - LICENSE
      - '**.md'
      - '.github/rulesets/**'
      - .github/workflows/faux-crucible-ci.yaml
      - .github/workflows/faux-benchmark-crucible-ci.yaml
      - .github/workflows/faux-core-crucible-ci.yaml
      - .github/workflows/faux-core-release-crucible-ci.yaml
      - .github/workflows/faux-tool-crucible-ci.yaml
      - '.github/runners/**'
      - 'docs/**'
  workflow_dispatch:

jobs:
  call-core-crucible-ci:
    strategy:
      fail-fast: false
      matrix:
        repos:
        - subproject: "CommonDataModel"
          subproject_dir: "CommonDataModel"
          branch: "master"
          userenv_filter: "minimal"
          force_controller_build: "no"
        - subproject: "rickshaw"
          subproject_dir: "rickshaw"
          branch: "master"
          userenv_filter: "all"
          force_controller_build: "no"
    uses: ./.github/workflows/core-crucible-ci.yaml
    with:
      ci_target: "${{ matrix.repos.subproject }}"
      ci_target_dir: "${{ matrix.repos.subproject_dir }}"
      ci_target_branch: "${{ matrix.repos.branch }}"
      crucible_ci_test: "yes"
      crucible_ci_test_branch: "${{ github.ref }}"
      github_workspace: "$GITHUB_WORKSPACE"
      userenv_filter: ${{ matrix.repos.userenv_filter }}
    secrets:
      ci_registry_auth: ${{ secrets.CRUCIBLE_CI_ENGINES_REGISTRY_AUTH }}
      quay_oauth_token: ${{ secrets.CRUCIBLE_QUAYIO_OAUTH_TOKEN }}

  call-core-release-crucible-ci:
    strategy:
      fail-fast: false
      matrix:
        repos:
        - subproject: "crucible"
          subproject_dir: "crucible"
          branch: "master"
          userenv_filter: "unique"
          force_controller_build: "yes"
    uses: ./.github/workflows/core-release-crucible-ci.yaml
    with:
      ci_target: "${{ matrix.repos.subproject }}"
      ci_target_dir: "${{ matrix.repos.subproject_dir }}"
      ci_target_branch: "${{ matrix.repos.branch }}"
      crucible_ci_test: "yes"
      crucible_ci_test_branch: "${{ github.ref }}"
      github_workspace: "$GITHUB_WORKSPACE"
      userenv_filter: ${{ matrix.repos.userenv_filter }}
      force_controller_build: "${{ matrix.repos.force_controller_build }}"
    secrets:
      ci_registry_auth: ${{ secrets.CRUCIBLE_CI_ENGINES_REGISTRY_AUTH }}
      quay_oauth_token: ${{ secrets.CRUCIBLE_QUAYIO_OAUTH_TOKEN }}

  test-core-crucible-ci-complete:
    runs-on: [ self-hosted, workflow-overhead ]
    needs:
    - call-core-crucible-ci
    - call-core-release-crucible-ci
    steps:
    - name: Confirm Success
      run: echo "test-core-crucible-ci-complete"
