name: tool-crucible-ci

on:
  workflow_call:
    inputs:
      ci_target:
        required: true
        type: string
      crucible_ci_test:
        required: false
        type: string
      ci_target_branch:
        required: true
        type: string
      crucible_ci_test_branch:
        required: false
        type: string
      github_workspace:
        required: true
        type: string
    secrets:
      registry_auth:
        required: false
      ci_registry_auth:
        required: false
      production_registry_auth:
        required: false
      quay_oauth_token:
        required: false

concurrency:
  group: ${{ inputs.ci_target }}/${{ github.ref }}/tool-crucible-ci
  cancel-in-progress: true

env:
  GITHUB_WORKSPACE: ${{ inputs.github_workspace }}

jobs:
  gen-params:
    runs-on: [ self-hosted, workflow-overhead ]
    timeout-minutes: 10
    outputs:
      github_hosted_jobs: ${{ steps.get-job-parameters-github.outputs.jobs }}
      repo_name: ${{ steps.get-repo-name.outputs.repo-name }}
    steps:

    - name: checkout crucible-ci default
      if: ${{ inputs.crucible_ci_test != 'yes' }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/crucible-ci
        ref: main
        path: crucible-ci
    - name: checkout crucible-ci crucible_ci_test
      if: ${{ inputs.crucible_ci_test == 'yes' }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/crucible-ci
        ref: ${{ inputs.crucible_ci_test_branch }}
        path: crucible-ci

    - name: checkout toolbox
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/toolbox
        ref: main
        path: toolbox
    - name: checkout rickshaw
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/rickshaw
        ref: master
        path: rickshaw
    - name: run get-job-parameters github
      id: get-job-parameters-github
      uses: ./crucible-ci/.github/actions/get-job-parameters
      with:
        runner-type: "github"
        benchmark: "fio"
        rickshaw-directory: "./rickshaw"
        toolbox-directory: "./toolbox"
    - name: run get-repo-name
      id: get-repo-name
      uses: ./crucible-ci/.github/actions/get-repo-name

  display-params:
    runs-on: [ self-hosted, workflow-overhead ]
    timeout-minutes: 10
    needs: gen-params
    steps:
    - name: Display github_hosted_jobs
      run: echo '${{ needs.gen-params.outputs.github_hosted_jobs }}' | jq .
    - name: Display repo_name
      run: echo '${{ needs.gen-params.outputs.repo_name }}'

  github-runners:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    needs:
    - gen-params
    - display-params
    strategy:
      fail-fast: false
      matrix:
        job: ${{ fromJSON(needs.gen-params.outputs.github_hosted_jobs) }}
    steps:
    - name: Matrix Parameters => (${{ matrix.job.enabled }}, ${{ matrix.job.endpoint }}, ${{ matrix.job.benchmark }}, ${{ matrix.job.userenv }})
      run: |
        echo "enabled=${{ matrix.job.enabled }}"
        echo "endpoint=${{ matrix.job.endpoint }}"
        echo "benchmark=${{ matrix.job.benchmark }}"
        echo "userenv=${{ matrix.job.userenv }}"

    - name: checkout crucible-ci default
      if: ${{ inputs.crucible_ci_test != 'yes' }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/crucible-ci
        ref: main
        path: crucible-ci
    - name: checkout crucible-ci crucible_ci_test
      if: ${{ inputs.crucible_ci_test == 'yes' }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/crucible-ci
        ref: ${{ inputs.crucible_ci_test_branch }}
        path: crucible-ci

    - name: checkout tool-${{ inputs.ci_target }}
      uses: actions/checkout@v4
      with:
        repository: perftool-incubator/tool-${{ inputs.ci_target }}
        ref: ${{ inputs.ci_target_branch }}
        path: "tool-${{ inputs.ci_target }}"

    - name: import ci secret
      env:
        ENGINE_REGISTRY_AUTH_SECRET: ${{ secrets.registry_auth != '' && secrets.registry_auth || secrets.ci_registry_auth }}
      if: ${{ env.ENGINE_REGISTRY_AUTH_SECRET != '' }}
      run: sudo bash -c "echo \"$ENGINE_REGISTRY_AUTH_SECRET\" > /root/crucible-ci-engines-token.json"
    - name: import production secret
      env:
        ENGINE_REGISTRY_AUTH_SECRET: ${{ secrets.production_registry_auth }}
      if: ${{ env.ENGINE_REGISTRY_AUTH_SECRET != '' }}
      run: sudo bash -c "echo \"$ENGINE_REGISTRY_AUTH_SECRET\" > /root/crucible-production-engines-token.json"

    - name: import quay oath token
      env:
        QUAY_OAUTH_TOKEN: ${{ secrets.quay_oauth_token }}
      if: ${{ env.QUAY_OAUTH_TOKEN != '' }}
      run: sudo bash -c "echo \"$QUAY_OAUTH_TOKEN\" > /root/quay-oauth.token"

    - name: run crucible-ci->integration-tests
      if: ${{ matrix.job.enabled }}
      uses: ./crucible-ci/.github/actions/integration-tests
      with:
        artifact_tag: "${{ inputs.ci_target }}__github-runners__${{ matrix.job.endpoint }}-${{ matrix.job.benchmark }}-${{ matrix.job.userenv }}"
        ci_endpoint: "${{ matrix.job.endpoint }}"
        scenarios: "${{ matrix.job.benchmark }}"
        userenvs: "${{ matrix.job.userenv }}"
        ci_target: "${{ inputs.ci_target }}"
        ci_target_dir: "${{ github.workspace }}/tool-${{ inputs.ci_target }}"
    - name: skip crucible-ci->integration-tests
      if: ${{ ! matrix.job.enabled }}
      run: echo "crucible-ci->integration-tests not enabled"

  tool-crucible-ci-complete:
    runs-on: [ self-hosted, workflow-overhead ]
    timeout-minutes: 10
    needs:
    - github-runners
    steps:
    - name: Confirm Success
      run: echo "tool-crucible-ci-complete"
